### ISSUE TITLE
Contact form field end hook?

### ISSUE THREAD

**Issue by Rubonnek** [hbstack/contact#6]
I'm using [Formailer](https://github.com/torrayne/formailer) as my contact form backend and it requires me to add a hidden `<input>` with name `_form_name` to the contact form.

It doesn't seem this module has a similar [`contact/form-field-end` hook](https://hbs.razonyang.com/v1/en/docs/advanced/hooks/). That's the only hook I need.

**Comment by razonyang** [comment]
Extra parameter would be better, since this module allows generating multiple forms, hooks will affect all forms.

Please upgrade to module's v0.2.0, and then append the following parameters.

```toml
# params.toml
[[hb.contact.extra_fields]]
name = "_form_name"
type = "hidden"
value = "contact"
```
